export enum LeaveType {
  ANNUAL = 'ANNUAL',
  SICK = 'SICK',
  MATERNITY = 'MATERNITY',
  PATERNITY = 'PATERNITY',
  UNPAID = 'UNPAID',
  COMPASSIONATE = 'COMPASSIONATE',
  STUDY = 'STUDY',
  BEREAVEMENT = 'BEREAVEMENT',
  OTHER = 'OTHER',
}